[package]
name = "leafadoo"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
flate2 = { version = "1.0.30", default-features = false, features = ["zlib"] }
serde = { version = "1.0.203", features = ["derive"] }
